// <auto-generated />
namespace CrownAIO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedAYCD_SolutionToAYCDSolution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedAYCD_SolutionToAYCDSolution));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131018384_changedAYCD_SolutionToAYCDSolution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
